import { Building2, Shield, Globe, Activity, Users, Zap, Target, TrendingUp, ArrowRight } from 'lucide-react'
import { motion } from 'framer-motion'
import { useNavigate } from 'react-router-dom'
import BaseInfoPage from '../../../components/common/BaseInfoPage'

export default function CompanyBriefPage() {
  const navigate = useNavigate()
  const fadeUp = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0, transition: { duration: 0.5 } }
  }

  return (
    <BaseInfoPage 
      title="Company Brief" 
      subtitle="Operational History // 0x01 // High Command" 
      icon={Building2}
    >
      <div className="space-y-8 text-muted-foreground font-light leading-relaxed">
        {/* Section 1: Strategic Introduction */}
        <p className="text-xl text-foreground font-medium">WebShark is a mission-driven intelligence firm dedicated to digital dominance.</p>
        <p>Founded in 2024, our objective has always been to level the playing field for growth teams by providing enterprise-grade armaments. We operate at the intersection of data science and architectural SEO, processing billions of signals to deliver absolute market clarity.</p>
        
        {/* Section 2: Operational Protocols */}
        <div className="grid md:grid-cols-2 gap-8 mt-12">
           <div className="p-8 border border-border bg-accent/5 industrial-corner hover:border-primary-blue/30 transition-all group">
              <div className="h-10 w-10 bg-primary-blue/10 flex items-center justify-center text-primary-blue mb-6 group-hover:bg-primary-blue group-hover:text-white transition-all">
                 <Shield className="h-5 w-5" />
              </div>
              <h4 className="font-bold text-foreground uppercase tracking-tight mb-4">Core Integrity</h4>
              <p className="text-sm">We maintain a Zero-Trust architecture across all data ingestion points, ensuring your competitive intelligence is air-gapped and secured.</p>
           </div>
           <div className="p-8 border border-border bg-accent/5 industrial-corner hover:border-primary-blue/30 transition-all group">
              <div className="h-10 w-10 bg-primary-blue/10 flex items-center justify-center text-primary-blue mb-6 group-hover:bg-primary-blue group-hover:text-white transition-all">
                 <Target className="h-5 w-5" />
              </div>
              <h4 className="font-bold text-foreground uppercase tracking-tight mb-4">Tactical Precision</h4>
              <p className="text-sm">Every directive generated by the WebShark neural engine is backed by verifiable telemetry and multi-vector data validation.</p>
           </div>
        </div>

        {/* Section 3: Global Infrastructure */}
        <motion.div initial="hidden" whileInView="show" viewport={{ once: true }} variants={fadeUp} className="mt-32">
           <div className="p-12 border border-border bg-card industrial-corner relative overflow-hidden">
              <div className="absolute top-0 right-0 p-8 opacity-5">
                 <Globe className="h-64 w-64 text-primary-blue" />
              </div>
              <div className="relative z-10">
                 <h3 className="font-display text-3xl font-bold uppercase tracking-tighter text-foreground mb-8">Global <span className="text-primary-blue">Infrastructure.</span></h3>
                 <p className="text-sm max-w-2xl mb-12">WebShark's infrastructure is distributed across 22 primary server regions, providing redundant telemetry paths and low-latency ingestion for mission-critical operations.</p>
                 <div className="grid grid-cols-2 lg:grid-cols-4 gap-8">
                    {[
                      { label: 'Active Nodes', value: '14,200+' },
                      { label: 'Ingestion Rate', value: '2.1 TB/s' },
                      { label: 'Global Uptime', value: '99.999%' },
                      { label: 'Encryption', value: 'AES-256' }
                    ].map((stat, i) => (
                      <div key={i}>
                         <p className="text-[10px] font-black text-muted-foreground uppercase tracking-widest mb-1">{stat.label}</p>
                         <p className="text-2xl font-black text-foreground">{stat.value}</p>
                      </div>
                    ))}
                 </div>
              </div>
           </div>
        </motion.div>

        {/* Section 4: Operational Evolution */}
        <motion.div initial="hidden" whileInView="show" viewport={{ once: true }} variants={fadeUp} className="mt-32">
           <h3 className="font-display text-3xl font-bold uppercase tracking-tighter text-foreground mb-12 text-center">Operational <span className="text-primary-blue">Evolution.</span></h3>
           <div className="space-y-12 max-w-3xl mx-auto">
              {[
                { year: '2024', event: 'WebShark Genesis Protocol initiated. First neural crawler deployment in North American sectors.' },
                { year: '2025', event: 'Global Node Expansion. Integration of real-time SERP volatility telemetry across 140+ countries.' },
                { year: '2026', event: 'Tactical AI V4.0. Launch of predictive scaling models and automated remediation directives.' }
              ].map((m, i) => (
                <div key={i} className="flex gap-8 items-start group">
                   <div className="h-16 w-16 bg-primary-blue/10 border border-primary-blue/20 flex items-center justify-center shrink-0 text-primary-blue font-black text-sm group-hover:bg-primary-blue group-hover:text-white transition-all">
                      {m.year}
                   </div>
                   <div className="pt-2">
                      <p className="text-sm text-foreground font-bold uppercase tracking-tight mb-2">Milestone_{i+1}</p>
                      <p className="text-xs text-muted-foreground leading-relaxed">{m.event}</p>
                   </div>
                </div>
              ))}
           </div>
        </motion.div>

        {/* Section 5: Command Leadership & CTA */}
        <motion.div initial="hidden" whileInView="show" viewport={{ once: true }} variants={fadeUp} className="mt-40 mb-20">
           <div className="p-16 border border-primary-blue/30 bg-primary-blue/5 industrial-corner relative overflow-hidden">
              <div className="grid lg:grid-cols-2 gap-12 items-center relative z-10">
                 <div>
                    <h3 className="font-display text-3xl font-bold uppercase tracking-tighter text-foreground mb-8">Command <span className="text-primary-blue">Leadership.</span></h3>
                    <div className="grid grid-cols-2 gap-4">
                       {[
                         { name: 'Dr. Elias Vance', role: 'Chief Architect' },
                         { name: 'Sarah Chen', role: 'Head of Intel' },
                         { name: 'Marcus Thorne', role: 'Ops Director' },
                         { name: 'Elena Rossi', role: 'Chief Scientist' }
                       ].map((leader, i) => (
                         <div key={i} className="p-4 border border-border bg-background">
                            <h4 className="text-[10px] font-black text-foreground uppercase tracking-widest mb-1">{leader.name}</h4>
                            <p className="text-[8px] font-bold text-primary-blue uppercase tracking-widest">{leader.role}</p>
                         </div>
                       ))}
                    </div>
                 </div>
                 <div className="text-center lg:text-right">
                    <h2 className="font-display text-4xl font-bold uppercase tracking-tighter text-foreground mb-6">Authorize <span className="text-primary-blue">Deployment.</span></h2>
                    <div className="flex flex-col sm:flex-row lg:justify-end gap-4">
                       <button 
                          onClick={() => navigate('/contact')}
                          className="inline-flex items-center justify-center gap-4 px-10 py-4 bg-primary-blue text-white font-black text-[11px] uppercase tracking-[0.3em] hover:bg-primary-blue/90 transition-all shadow-neon-blue"
                        >
                          Initialize Operation <ArrowRight className="h-4 w-4" />
                       </button>
                       <button 
                          onClick={() => navigate('/pricing')}
                          className="inline-flex items-center justify-center gap-4 px-10 py-4 bg-background border border-border text-foreground font-black text-[11px] uppercase tracking-[0.3em] hover:bg-accent transition-all"
                        >
                          View Pricing <Zap className="h-4 w-4" />
                       </button>
                    </div>
                 </div>
              </div>
           </div>
        </motion.div>
      </div>
    </BaseInfoPage>
  )
}
