import { Building2, Shield, Globe, Activity, Users, Zap, Target, TrendingUp, ArrowRight } from 'lucide-react'
import { motion } from 'framer-motion'
import BaseInfoPage from '../../../components/common/BaseInfoPage'

export default function CompanyBriefPage() {
  const fadeUp = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0, transition: { duration: 0.5 } }
  }

  return (
    <BaseInfoPage 
      title="Company Brief" 
      subtitle="Operational History // 0x01 // High Command" 
      icon={Building2}
    >
      <div className="space-y-8 text-muted-foreground font-light leading-relaxed">
        <p className="text-xl text-foreground font-medium">WebShark is a mission-driven intelligence firm dedicated to digital dominance.</p>
        <p>Founded in 2024, our objective has always been to level the playing field for growth teams by providing enterprise-grade armaments. We operate at the intersection of data science and architectural SEO, processing billions of signals to deliver absolute market clarity.</p>
        
        {/* Section 2: Operational Protocols */}
        <div className="grid md:grid-cols-2 gap-8 mt-12">
           <div className="p-8 border border-border bg-accent/5 industrial-corner hover:border-primary-blue/30 transition-all group">
              <div className="h-10 w-10 bg-primary-blue/10 flex items-center justify-center text-primary-blue mb-6 group-hover:bg-primary-blue group-hover:text-white transition-all">
                 <Shield className="h-5 w-5" />
              </div>
              <h4 className="font-bold text-foreground uppercase tracking-tight mb-4">Core Integrity</h4>
              <p className="text-sm">We maintain a Zero-Trust architecture across all data ingestion points, ensuring your competitive intelligence is air-gapped and secured.</p>
           </div>
           <div className="p-8 border border-border bg-accent/5 industrial-corner hover:border-primary-blue/30 transition-all group">
              <div className="h-10 w-10 bg-primary-blue/10 flex items-center justify-center text-primary-blue mb-6 group-hover:bg-primary-blue group-hover:text-white transition-all">
                 <Target className="h-5 w-5" />
              </div>
              <h4 className="font-bold text-foreground uppercase tracking-tight mb-4">Tactical Precision</h4>
              <p className="text-sm">Every directive generated by the WebShark neural engine is backed by verifiable telemetry and multi-vector data validation.</p>
           </div>
        </div>

        {/* Section 3: Global Infrastructure */}
        <motion.div initial="hidden" whileInView="show" viewport={{ once: true }} variants={fadeUp} className="mt-32">
           <div className="p-12 border border-border bg-card industrial-corner relative overflow-hidden">
              <div className="absolute top-0 right-0 p-8 opacity-5">
                 <Globe className="h-64 w-64 text-primary-blue" />
              </div>
              <div className="relative z-10">
                 <h3 className="font-display text-3xl font-bold uppercase tracking-tighter text-foreground mb-8">Global <span className="text-primary-blue">Infrastructure.</span></h3>
                 <p className="text-sm max-w-2xl mb-12">WebShark's infrastructure is distributed across 22 primary server regions, providing redundant telemetry paths and low-latency ingestion for mission-critical operations.</p>
                 <div className="grid grid-cols-2 lg:grid-cols-4 gap-8">
                    {[
                      { label: 'Active Nodes', value: '14,200+' },
                      { label: 'Ingestion Rate', value: '2.1 TB/s' },
                      { label: 'Global Uptime', value: '99.999%' },
                      { label: 'Encryption', value: 'AES-256' }
                    ].map((stat, i) => (
                      <div key={i}>
                         <p className="text-[10px] font-black text-muted-foreground uppercase tracking-widest mb-1">{stat.label}</p>
                         <p className="text-2xl font-black text-foreground">{stat.value}</p>
                      </div>
                    ))}
                 </div>
              </div>
           </div>
        </motion.div>

        {/* Section 4: Strategic Timeline */}
        <motion.div initial="hidden" whileInView="show" viewport={{ once: true }} variants={fadeUp} className="mt-32">
           <h3 className="font-display text-3xl font-bold uppercase tracking-tighter text-foreground mb-12 text-center">Operational <span className="text-primary-blue">Evolution.</span></h3>
           <div className="space-y-12 max-w-3xl mx-auto">
              {[
                { year: '2024', event: 'WebShark Genesis Protocol initiated. First neural crawler deployment in North American sectors.' },
                { year: '2025', event: 'Global Node Expansion. Integration of real-time SERP volatility telemetry across 140+ countries.' },
                { year: '2026', event: 'Tactical AI V4.0. Launch of predictive scaling models and automated remediation directives.' }
              ].map((m, i) => (
                <div key={i} className="flex gap-8 items-start group">
                   <div className="h-16 w-16 bg-primary-blue/10 border border-primary-blue/20 flex items-center justify-center shrink-0 text-primary-blue font-black text-sm group-hover:bg-primary-blue group-hover:text-white transition-all">
                      {m.year}
                   </div>
                   <div className="pt-2">
                      <p className="text-sm text-foreground font-bold uppercase tracking-tight mb-2">Milestone_{i+1}</p>
                      <p className="text-xs text-muted-foreground leading-relaxed">{m.event}</p>
                   </div>
                </div>
              ))}
           </div>
        </motion.div>

        {/* Section 5: Leadership Matrix */}
        <motion.div initial="hidden" whileInView="show" viewport={{ once: true }} variants={fadeUp} className="mt-32">
           <h3 className="font-display text-3xl font-bold uppercase tracking-tighter text-foreground mb-12">Command <span className="text-primary-blue">Leadership.</span></h3>
           <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
              {[
                { name: 'Dr. Elias Vance', role: 'Chief Architect' },
                { name: 'Sarah Chen', role: 'Head of Intel' },
                { name: 'Marcus Thorne', role: 'Ops Director' },
                { name: 'Elena Rossi', role: 'Chief Scientist' }
              ].map((leader, i) => (
                <div key={i} className="p-6 border border-border bg-background hover:border-primary-blue transition-all cursor-default">
                   <h4 className="text-xs font-black text-foreground uppercase tracking-widest mb-1">{leader.name}</h4>
                   <p className="text-[10px] font-bold text-primary-blue uppercase tracking-widest">{leader.role}</p>
                </div>
              ))}
           </div>
        </motion.div>

        {/* Section 6: Values & Commitment */}
        <motion.div initial="hidden" whileInView="show" viewport={{ once: true }} variants={fadeUp} className="mt-32 p-12 border border-border bg-accent/5 industrial-corner">
           <div className="grid lg:grid-cols-2 gap-16 items-center">
              <div>
                 <h3 className="font-display text-3xl font-bold uppercase tracking-tighter text-foreground mb-8">Core <span className="text-primary-blue">Protocols.</span></h3>
                 <p className="text-sm leading-relaxed mb-8">Our operations are governed by three non-negotiable protocols that ensure the integrity of the WebShark network and the success of our operatives.</p>
                 <div className="space-y-4">
                    {['Radical Data Transparency', 'Zero-Latency Response', 'Ethical Neural Engineering'].map(v => (
                      <div key={v} className="flex items-center gap-4 p-4 bg-background border border-border">
                         <Activity className="h-4 w-4 text-primary-blue/50" />
                         <span className="text-[10px] font-black uppercase tracking-widest text-foreground">{v}</span>
                      </div>
                    ))}
                 </div>
              </div>
              <div className="aspect-square border border-border bg-background flex items-center justify-center relative overflow-hidden group">
                 <div className="absolute inset-0 grid-pattern opacity-10" />
                 <Shield className="h-32 w-32 text-primary-blue opacity-10 group-hover:scale-110 transition-transform duration-1000" />
                 <div className="absolute bottom-4 text-center">
                    <p className="text-[8px] font-black uppercase tracking-[0.4em] text-muted-foreground">Certified_Operational_Integrity</p>
                 </div>
              </div>
           </div>
        </motion.div>

        {/* Section 7: Final CTA */}
        <motion.div initial="hidden" whileInView="show" viewport={{ once: true }} variants={fadeUp} className="mt-40 mb-20 text-center">
           <div className="p-16 border border-primary-blue/30 bg-primary-blue/5 industrial-corner relative overflow-hidden group">
              <div className="relative z-10">
                 <h2 className="font-display text-4xl lg:text-5xl font-bold uppercase tracking-tighter text-foreground mb-8">Authorize Your <span className="text-primary-blue">Deployment.</span></h2>
                 <p className="text-base text-muted-foreground font-light max-w-xl mx-auto mb-10">Join the thousands of global operatives who rely on WebShark for absolute market intelligence and technical dominance.</p>
                 <button className="px-12 py-5 bg-primary-blue text-white font-black text-[11px] uppercase tracking-[0.3em] hover:bg-primary-blue/90 transition-all shadow-neon-blue flex items-center gap-4 mx-auto">
                    Initialize Operation <ArrowRight className="h-4 w-4" />
                 </button>
              </div>
           </div>
        </motion.div>
      </div>
    </BaseInfoPage>
  )
}
